### ISSUE TITLE
Current DomainCrawler runs into AssertionError due to url being None

### ISSUE THREAD

**Issue by daringer** [snorrwe/lollygag#33]
## Expected Behavior
No Assertion is triggered by using the DomainCrawler

## Actual Behavior
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home//dev/lollygag/lollygag/services/work/work_service.py", line 43, in __worker
    task()
  File "/home//dev/lollygag/lollygag/core/crawlers/jobs/crawl_job.py", line 13, in __call__
    self.run()
  File "/home//dev/lollygag/lollygag/core/crawlers/jobs/crawl_job.py", line 29, in run
    self.crawler.process_links(url, result.links)
  File "/home//dev/lollygag/lollygag/core/crawlers/crawler.py", line 121, in process_links
    processed_link = self.process_link(origin, link)
  File "/home//dev/lollygag/lollygag/core/crawlers/domain_crawler.py", line 20, in process_link
    if get_domain(result) != self.domain:
  File "/home//dev/lollygag/lollygag/utility/url.py", line 30, in get_domain
    assert url is not None
AssertionError

## Steps to Reproduce the Problem
  1. run the code provided in the README 
  
## Specifications
  - Version: git
  - Platform: linux

## Investigation
`Crawler::process_link()` might return `None`, which is not handled appropriately within `DomainCrawler::process_link()`

## Solution
Simply extend the if statement inside `DomainCrawler::process_link()` to check for `None` and thus not execute the second expression, which contains the assert-throwing `get_domain()` call.

PR in a minute, hacktoberfest, yeah :smile:

**Comment by daringer** [comment]
hope it's ok, for me it looks better than before...
